name: Creating Build for Node App

on: 
  push:
    branches: 
      - practice-lab 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules # Cache path
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: npm install

      
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}  # Needed for PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         args: >
          -Dsonar.projectKey=DevOpsByOmer_nodejs-p
          -Dsonar.organization=OmerMohammed
          -Dsonar.host.url=https://sonarcloud.io
      

      - name: Slack Notification
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'We have sent the GitHub Action notification success message'  
          SLACK_CHANNEL: '#github_actions'
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          SLACK_TITLE: 'Slack Notification'

      - name: E-Mail Notification
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Workflow finished
          body: Job ${{ job.status }}
          to: dvop.omer@gmail.com 
          from: Github-action
    
      
        

