name: Testing in dev environment
on:
  push:
    branches:
      - dev
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     

      - name: Install dependencies
        run: npm install

      - name: Building
        run: npm run build

      - name: Slack Notifications
        uses: act10n/slack@v1
        with:
          status: ${{job.status}}
          steps:  ${{toJson(steps)}}
          channel: '#github_actions'
        if: always ()
          
      
        
        
