name: Deploy Node.js App    

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Install dependencies
        run: npm install 


      - name: start react-app
        run: npm start

     
        
